# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZtQV0abUklbOz_xmDpQ8HLMJlyS1wA6
"""

!pip install librosa
import librosa
import librosa.display # You need this in librosa to be able to plot
import os
import matplotlib.pyplot as plt

clip_dir = os.path.join("sw02005.sph")

def load(start,end):#function to splice audio start=start time , end = end time in seconds
  audio,sr = librosa.load(clip_dir,sr=8000,offset=start,duration=end) # audio is a numpy array
  return audio,sr

#example
audio,sr=load(1,4) # loads audio from t=1 to t=4 seconds
fig, ax = plt.subplots(figsize=(15,8))
librosa.display.waveplot(audio, sr=sr, ax=ax)
ax.set(title="sw02005.sph waveform")